In [8]:

import numpy as np
import pandas as pd
import json
from ortools.constraint_solver import pywrapcp, routing_enums_pb2
from multiprocessing import Pool
import warnings
warnings.filterwarnings("ignore")


heroes = pd.read_csv('data_heroes.csv')
objects = pd.read_csv('data_objects.csv')


dis = pd.read_csv('dist_objects.csv')
d0 = pd.read_csv('dist_start.csv')
d0['end'] = 0
d0.index = range(0,len(d0))
d0 = d0.iloc[:,1:]
dis = pd.concat([d0,dis],axis=1)

d0 = d0.T
d0 = pd.concat([d0.iloc[:,:2],d0], axis =1)
d0.iloc[:,:2] = 0
d0.columns = dis.columns
dis = pd.concat([d0,dis],axis=0)
dis.columns = [0,-1]+list(np.arange(700)+1)
dis.index = dis.columns

heroes = heroes.iloc[:20]


dis = dis.loc[[0,-1]+[-1]*6*20+list(np.arange(len(dis)-2)+1),[0,-1]+[-1]*6*20+list(np.arange(len(dis)-2)+1)]
dis

,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,691,692,693,694,695,696,697,698,699,700
0,0,0,0,0,0,0,0,0,0,0,...,426,493,453,426,666,720,693,600,480,120
-1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,720,0,0,0,0,0,0,0,0,0,...,567,600,647,760,240,0,233,187,747,853
697,693,0,0,0,0,0,0,0,0,0,...,527,553,573,700,233,233,0,160,653,800
698,600,0,0,0,0,0,0,0,0,0,...,467,500,520,653,80,187,160,0,647,747
699,480,0,0,0,0,0,0,0,0,0,...,573,573,267,680,693,747,653,647,0,587
700,120,0,0,0,0,0,0,0,0,0,...,533,527,540,453,793,853,800,747,587,0

In [2]:
objects = objects.loc[[1,1]+list(objects.index)]
objects.index=np.arange(len(objects))-1
objects.loc[:,'reward']=100 

objects.iloc[:2]=1
objects = objects.loc[dis.index]
objects['start'] = (objects['day_open']-1)*24*60
objects['finish'] =(objects['day_open'])*24*60
objects['finish'].iloc[:2] = 7*24*60
objects.loc[[0,-1],'reward'] = 0
objects['day_open'].iloc[2:122] = [1,2,3,4,5,6]*20
objects['start'].iloc[2:2+6*20] = objects['day_open'].iloc[2:2+6*20]*24*60-1
objects['finish'].iloc[2:2+6*20] =objects['day_open'].iloc[2:2+6*20]*24*60+1
objects

      object_id  day_open  reward  start  finish
 0            1         1       0      0   10080
-1            1         1       0      0   10080
-1            1         1       0   1439    1441
-1            1         2       0   2879    2881
-1            1         3       0   4319    4321
...         ...       ...     ...    ...     ...
 696        696         6     100   7200    8640
 697        697         4     100   4320    5760
 698        698         6     100   7200    8640
 699        699         3     100   2880    4320
 700        700         7     100   8640   10080

[822 rows x 5 columns]

In [ ]:
dis = dis.iloc[:200,:200]
objects = objects.iloc[:200,:]

In [4]:


data = {}
data['time_matrix'] = dis.values.tolist()
data['time_windows'] = objects[['start','finish']].astype(int).values.tolist()
data['demands'] = objects['reward'].to_list()

data['num_vehicles'] = len(heroes['move_points'].to_list())
data['vehicle_capacities'] = heroes['move_points'].to_list()
data['num'] = len(data['time_matrix'])

In [ ]:
"""Vehicles Routing Problem (VRP) with Time Windows and Capacity Constraints."""

from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp

def export_solution(data, manager, routing, solution):
    """Exports solution to a JSON file."""
    time_dimension = routing.GetDimensionOrDie("Time")
    capacity_dimension = routing.GetDimensionOrDie("Capacity")
    
    routes_data = []
    total_time = 0
    alst = []
    for vehicle_id in range(data["num_vehicles"]):
        index = routing.Start(vehicle_id)
        route_stops = []
        route_times = []
        route_loads = []
        route_slack=[]
        
        while not routing.IsEnd(index):
            node_index = manager.IndexToNode(index)
            time_var = time_dimension.CumulVar(index)
            load_var = capacity_dimension.CumulVar(index)
            
            route_stops.append(node_index)
            # Store the specific value assigned by the solver
            route_times.append(solution.Value(time_var)) 
            route_loads.append(solution.Value(load_var))
    
            index = solution.Value(routing.NextVar(index))
        
        # End node (depot)
        node_index = manager.IndexToNode(index)
        time_var = time_dimension.CumulVar(index)
        load_var = capacity_dimension.CumulVar(index)
        route_stops.append(node_index)
        route_times.append(solution.Value(time_var))
        route_loads.append(solution.Value(load_var))
        
        route_time = solution.Value(time_var)
        total_time += route_time

        if len(route_stops)>2:
            routes_data.append({
                "vehicle_id": vehicle_id,
                'move_point':heroes['move_points'].to_list()[vehicle_id],
                "stops": route_stops,
                'days':[objects['day_open'].to_list()[i] for i in route_stops],
                "arrival_times": route_times,
                "loads": route_loads,
                "route_duration": route_time
            })
        alst += route_stops
    print(f'Drop stops {len(set(range(data['num']))-set(alst))}')
    return routes_data


# Create the routing index manager.
manager = pywrapcp.RoutingIndexManager(
    len(data["time_matrix"]), data["num_vehicles"], [0]*data['num_vehicles'],[1]*data['num_vehicles']
)

# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)

# Create and register a transit callback.
def time_callback(from_index, to_index):
    """Returns the travel time between the two nodes."""
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return data["time_matrix"][from_node][to_node]+3

transit_callback_index = routing.RegisterTransitCallback(time_callback)

# Define cost of each arc.
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

# Add Time Windows constraint.
time = "Time"
routing.AddDimension(
    transit_callback_index,
    30000,  # allow waiting time
    7*24*60,  # maximum time per vehicle
    True,  # Don't force start cumul to zero.
    time,
)
time_dimension = routing.GetDimensionOrDie(time)
# Add time window constraints for each location except depot.
for location_idx, time_window in enumerate(data["time_windows"]):
    if location_idx in [0,1]:
        continue
    index = manager.NodeToIndex(location_idx)
    time_dimension.CumulVar(index).SetRange(time_window[0], time_window[1])
# Add time window constraints for each vehicle start node.
for vehicle_id in range(data["num_vehicles"]):
    index = routing.Start(vehicle_id)
    time_dimension.CumulVar(index).SetRange(
        data["time_windows"][0][0], data["time_windows"][0][1]
    )

# Instantiate route start and end times to produce feasible times.
for i in range(data["num_vehicles"]):
    routing.AddVariableMinimizedByFinalizer(
        time_dimension.CumulVar(routing.Start(i))
    )

# --- NEW: Add Capacity Constraint ---
# Create and register a demand callback.
def demand_callback(from_index, to_index):
    """Returns the travel time between the two nodes."""
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return data["time_matrix"][from_node][to_node]+data['demands'][from_node]

demand_callback_index = routing.RegisterTransitCallback(demand_callback)

# Add Capacity constraint to the model.
routing.AddDimensionWithVehicleCapacity(
    demand_callback_index,
    12000,  # null capacity slack
    data["vehicle_capacities"],  # vehicle maximum capacities
    True,  # start cumul to zero
    "Capacity",
)

solver = routing.solver()

for i in range(data['num']):
    index = manager.IndexToNode(i)
    cumul = time_dimension.CumulVar(index)
    slack = time_dimension.SlackVar(index)
    #cumul.SetRange(0, 1000*(slack==0))

cap_dimension = routing.GetDimensionOrDie("Capacity")
for node in range(2, 122):
    index = manager.IndexToNode(node)
    #solver.Add(routing.VehicleVar(index)==int((node-2)//7))


for node in range(2, len(data['time_matrix'])):
    index = manager.IndexToNode(node)
    routing.AddDisjunction([index], 100000)
    #cap_dimension.SlackVar(index).SetRange(0,200)


# Setting first solution heuristic.
search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
)

# Solve the problem.
solution = routing.SolveWithParameters(search_parameters)

print('Done')
# Print solution on console.
if solution:
    routes_data=export_solution(data, manager, routing, solution)
else:
    print("No solution found!")

In [ ]:
submit_csv = pd.DataFrame()
for i in routes_data:

    pf = objects.iloc[i['stops'][1:-1]]
    pf['hero_id'] = heroes.iloc[i['vehicle_id']]['hero_id']
    pf['num']= range(len(pf))
    pf['move'] = i['move_point']
    pf['windows'] = i['arrival_times'][1:-1]
    submit_csv = pd.concat([submit_csv, pf])

submit_csv = submit_csv.sort_values(['hero_id', 'num'])   

submit_csv

     object_id  day_open  reward  start  finish  hero_id  num  move  windows
 17         17         1     100      0    1440        1    0  1700      283
 44         44         1     100      0    1440        1    1  1700      893
 60         60         1     100      0    1440        1    2  1700      996
-1           1         1       0   1439    1441        1    3  1700     1439
 23         23         2     100   1440    2880        1    4  1700     1442
..         ...       ...     ...    ...     ...      ...  ...   ...      ...
-1           1         3       0   4319    4321       20    6  1560     4319
-1           1         4       0   5759    5761       20    7  1560     5759
-1           1         5       0   7199    7201       20    8  1560     7199
-1           1         6       0   8639    8641       20    9  1560     8639
 66         66         7     100   8640   10080       20   10  1560     8642

[198 rows x 9 columns]

In [ ]:
submit_csv = submit_csv.loc[submit_csv['reward']!=0]
submit_csv[['hero_id','object_id']].to_csv('submit.csv', index=False)

In [ ]:
routes_data

[{'vehicle_id': 0,
  'move_point': 1700,
  'stops': [0, 138, 165, 181, 2, 144, 3, 4, 123, 23, 18, 7, 172, 1],
  'days': [1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5, 6, 7, 1],
  'arrival_times': [0,
   283,
   893,
   996,
   1439,
   1442,
   2879,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642,
   8645],
  'loads': [0,
   280,
   987,
   1187,
   1287,
   1287,
   1387,
   1387,
   1387,
   1487,
   1487,
   1487,
   1487,
   1587],
  'route_duration': 8645},
 {'vehicle_id': 1,
  'move_point': 1560,
  'stops': [0,
   176,
   178,
   177,
   191,
   145,
   56,
   150,
   51,
   125,
   46,
   124,
   29,
   24,
   13,
   141,
   1],
  'days': [1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 7, 1],
  'arrival_times': [0,
   349,
   377,
   405,
   555,
   651,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642,
   8645],
  'loads': [0,
   346,
   471,
   596,
   843,
   1036,
   1136,
   1136,
   1236,
   1236,
   1336,
   1336,
   1436,
   1436,
   1436,
   1436,
   1536],
  'route_duration': 8645},
 {'vehicle_id': 2,
  'move_point': 1700,
  'stops': [0, 186, 62, 152, 57, 132, 52, 129, 35, 30, 19, 127, 1],
  'days': [1, 1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 7, 1],
  'arrival_times': [0,
   216,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642,
   8645],
  'loads': [0, 213, 313, 313, 413, 413, 513, 513, 613, 613, 613, 613, 713],
  'route_duration': 8645},
 {'vehicle_id': 3,
  'move_point': 1700,
  'stops': [0, 182, 135, 20, 63, 134, 58, 133, 41, 36, 25, 160, 1],
  'days': [1, 1, 1, 1, 2, 3, 3, 4, 4, 5, 6, 7, 1],
  'arrival_times': [0,
   496,
   572,
   1439,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642,
   8645],
  'loads': [0, 493, 666, 766, 766, 766, 866, 866, 966, 966, 966, 966, 1066],
  'route_duration': 8645},
 {'vehicle_id': 4,
  'move_point': 1560,
  'stops': [0, 68, 158, 21, 64, 136, 47, 42, 31, 188, 1],
  'days': [1, 1, 2, 2, 3, 4, 4, 5, 6, 7, 1],
  'arrival_times': [0,
   1439,
   1442,
   2879,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642,
   8645],
  'loads': [0, 0, 0, 100, 100, 100, 200, 200, 200, 200, 300],
  'route_duration': 8645},
 {'vehicle_id': 5,
  'move_point': 1560,
  'stops': [0, 74, 159, 69, 22, 137, 53, 48, 37, 1],
  'days': [1, 1, 2, 2, 3, 4, 4, 5, 6, 1],
  'arrival_times': [0, 1439, 1442, 2879, 4319, 4322, 5759, 7199, 8639, 8642],
  'loads': [0, 0, 0, 100, 100, 100, 200, 200, 200, 200],
  'route_duration': 8642},
 {'vehicle_id': 6,
  'move_point': 1560,
  'stops': [0, 80, 163, 75, 148, 70, 143, 59, 54, 43, 1],
  'days': [1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 1],
  'arrival_times': [0,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642],
  'loads': [0, 0, 0, 100, 100, 200, 200, 300, 300, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 7,
  'move_point': 1560,
  'stops': [0, 86, 166, 81, 151, 76, 147, 65, 60, 49, 1],
  'days': [1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 1],
  'arrival_times': [0,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642],
  'loads': [0, 0, 0, 100, 100, 200, 200, 300, 300, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 8,
  'move_point': 1560,
  'stops': [0, 92, 168, 87, 161, 82, 149, 71, 66, 55, 1],
  'days': [1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 1],
  'arrival_times': [0,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642],
  'loads': [0, 0, 0, 100, 100, 200, 200, 300, 300, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 9,
  'move_point': 1560,
  'stops': [0, 98, 174, 93, 164, 88, 156, 77, 72, 61, 1],
  'days': [1, 1, 2, 2, 3, 3, 4, 4, 5, 6, 1],
  'arrival_times': [0,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   8639,
   8642],
  'loads': [0, 0, 0, 100, 100, 200, 200, 300, 300, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 10,
  'move_point': 1560,
  'stops': [0, 104, 180, 99, 179, 94, 162, 83, 146, 78, 67, 1],
  'days': [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 1],
  'arrival_times': [0,
   1439,
   1442,
   2879,
   2882,
   4319,
   4322,
   5759,
   5762,
   7199,
   8639,
   8642],
  'loads': [0, 0, 0, 100, 100, 200, 200, 300, 300, 400, 400, 400],
  'route_duration': 8642},
 {'vehicle_id': 11,
  'move_point': 1560,
  'stops': [0, 26, 105, 183, 100, 173, 89, 153, 84, 128, 73, 1],
  'days': [1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 1],
  'arrival_times': [0,
   1439,
   2879,
   2882,
   4319,
   4322,
   5759,
   5762,
   7199,
   7202,
   8639,
   8642],
  'loads': [0, 0, 0, 0, 100, 100, 200, 200, 300, 300, 400, 400],
  'route_duration': 8642},
 {'vehicle_id': 12,
  'move_point': 1560,
  'stops': [0, 110, 27, 28, 184, 95, 155, 90, 130, 79, 1],
  'days': [1, 1, 2, 3, 4, 4, 5, 5, 6, 6, 1],
  'arrival_times': [0,
   1439,
   2879,
   4319,
   4322,
   5759,
   5762,
   7199,
   7202,
   8639,
   8642],
  'loads': [0, 0, 0, 0, 0, 100, 100, 200, 200, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 13,
  'move_point': 1900,
  'stops': [0, 32, 111, 192, 106, 185, 101, 167, 96, 140, 85, 1],
  'days': [1, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6, 1],
  'arrival_times': [0,
   1439,
   2879,
   2882,
   4319,
   4322,
   5759,
   5762,
   7199,
   7202,
   8639,
   8642],
  'loads': [0, 0, 0, 0, 100, 100, 200, 200, 300, 300, 400, 400],
  'route_duration': 8642},
 {'vehicle_id': 14,
  'move_point': 1560,
  'stops': [0, 116, 33, 34, 193, 5, 102, 142, 91, 1],
  'days': [1, 1, 2, 3, 4, 4, 5, 6, 6, 1],
  'arrival_times': [0, 1439, 2879, 4319, 4322, 5759, 7199, 7202, 8639, 8642],
  'loads': [0, 0, 0, 0, 0, 100, 100, 100, 200, 200],
  'route_duration': 8642},
 {'vehicle_id': 15,
  'move_point': 1560,
  'stops': [0, 38, 117, 198, 112, 197, 107, 6, 169, 97, 1],
  'days': [1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 1],
  'arrival_times': [0,
   1439,
   2879,
   2882,
   4319,
   4322,
   5759,
   7199,
   7202,
   8639,
   8642],
  'loads': [0, 0, 0, 0, 100, 100, 200, 200, 200, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 16,
  'move_point': 1560,
  'stops': [0, 8, 9, 118, 199, 113, 175, 108, 170, 103, 1],
  'days': [1, 1, 2, 3, 4, 4, 5, 5, 6, 6, 1],
  'arrival_times': [0,
   1439,
   2879,
   4319,
   4322,
   5759,
   5762,
   7199,
   7202,
   8639,
   8642],
  'loads': [0, 0, 0, 0, 0, 100, 100, 200, 200, 300, 300],
  'route_duration': 8642},
 {'vehicle_id': 17,
  'move_point': 1560,
  'stops': [0, 122, 196, 126, 50, 39, 10, 119, 189, 114, 171, 109, 154, 1],
  'days': [1, 1, 1, 1, 1, 2, 3, 4, 5, 5, 6, 6, 7, 1],
  'arrival_times': [0,
   416,
   592,
   902,
   1439,
   2879,
   4319,
   5759,
   5762,
   7199,
   7202,
   8639,
   8642,
   8645],
  'loads': [0,
   413,
   686,
   1093,
   1193,
   1193,
   1193,
   1193,
   1193,
   1293,
   1293,
   1393,
   1393,
   1493],
  'route_duration': 8645},
 {'vehicle_id': 18,
  'move_point': 1560,
  'stops': [0, 44, 45, 40, 11, 120, 194, 115, 157, 1],
  'days': [1, 1, 2, 3, 4, 5, 6, 6, 7, 1],
  'arrival_times': [0, 1439, 2879, 4319, 5759, 7199, 7202, 8639, 8642, 8645],
  'loads': [0, 0, 0, 0, 0, 0, 0, 100, 100, 200],
  'route_duration': 8645},
 {'vehicle_id': 19,
  'move_point': 1560,
  'stops': [0, 190, 195, 131, 14, 139, 15, 16, 17, 12, 121, 187, 1],
  'days': [1, 1, 1, 1, 1, 2, 2, 3, 4, 5, 6, 7, 1],
  'arrival_times': [0,
   336,
   732,
   1028,
   1439,
   1442,
   2879,
   4319,
   5759,
   7199,
   8639,
   8642,
   8645],
  'loads': [0,
   333,
   826,
   1219,
   1319,
   1319,
   1419,
   1419,
   1419,
   1419,
   1419,
   1419,
   1519],
  'route_duration': 8645}]